package io.github.manoelcampos.java2ts.javadoc;

import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.stream.Collectors;
import java.util.stream.Stream;

import static java.util.Objects.requireNonNullElse;

/**
 * The JavaDoc of a class, read from the XML file generated by the xml-doclet.
 *
 * @param comment the class comment
 * @param tags the class block tags (such as {@code @author}), except {@code @param}
 * @param params the {@code @param} tags of the class, where the key is the parameter name
 *               (used to document record components)
 * @param fields the comments of the fields, where the key is the field name
 * @param methods the comments of methods without parameters, where the key is the method name
 * @author Manoel Campos
 */
public record ClassDoc(String comment, List<DocTag> tags, Map<String, String> params,
                       Map<String, String> fields, Map<String, String> methods)
{
    /**
     * Creates a {@link ClassDoc}, validating the components and making immutable copies of collections.
     */
    public ClassDoc {
        comment = requireNonNullElse(comment, "");
        tags = List.copyOf(tags);
        params = Map.copyOf(params);
        fields = Map.copyOf(fields);
        methods = Map.copyOf(methods);
    }

    /**
     * {@return the full class documentation, including the comment and block tags}
     */
    public String fullComment() {
        final Stream<String> tagLines = tags.stream().map(DocTag::format);
        return Stream.concat(Stream.of(comment), tagLines).filter(line -> !line.isBlank()).collect(Collectors.joining("\n"));
    }

    /**
     * {@return the comment of a field or an empty string if there is none}
     * @param name the field name
     */
    public String field(final String name) {
        return fields.getOrDefault(name, "");
    }

    /**
     * {@return the comment of a method or an empty string if there is none}
     * @param name the method name
     */
    public String method(final String name) {
        return methods.getOrDefault(name, "");
    }

    /**
     * {@return the text of a {@code @param} tag or an empty string if there is none}
     * @param name the parameter name
     */
    public String param(final String name) {
        return params.getOrDefault(name, "");
    }

    /**
     * A JavaDoc block tag, such as {@code @author Manoel Campos}.
     * @param name the tag name, without the {@code @}
     * @param text the tag text
     */
    public record DocTag(String name, String text) {
        /**
         * {@return the tag as written in a JavaDoc}
         */
        public String format() {
            return "@%s %s".formatted(name, text).strip();
        }

        /**
         * {@return an Optional with the tag text, when this is the given tag}
         * @param tagName the tag name, without the {@code @}
         */
        public Optional<String> textIf(final String tagName) {
            return name.equals(tagName) ? Optional.of(text) : Optional.empty();
        }
    }
}
