package io.github.manoelcampos.java2ts.javadoc;

import java.lang.reflect.AnnotatedElement;
import java.lang.reflect.Field;
import java.lang.reflect.Method;
import java.lang.reflect.RecordComponent;
import java.nio.file.Path;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;

/**
 * Provides JavaDocs read from XML files generated by the
 * <a href="https://github.com/manticore-projects/xml-doclet">xml-doclet</a>.
 * @author Manoel Campos
 */
public final class XmlJavadoc implements Javadoc {
    private final Map<String, ClassDoc> classDocs;

    /**
     * Creates a Javadoc from the documentation of classes.
     * @param classDocs a map where each key is the canonical name of a class and the value is its documentation
     */
    public XmlJavadoc(final Map<String, ClassDoc> classDocs) {
        this.classDocs = Map.copyOf(classDocs);
    }

    /**
     * Loads the JavaDocs from XML files.
     * @param xmlFiles the XML files generated by the xml-doclet
     * @return a {@link Javadoc} with the documentation from all the files, or {@link Javadoc#NONE} if no file is given
     */
    public static Javadoc load(final List<Path> xmlFiles) {
        if (xmlFiles.isEmpty())
            return Javadoc.NONE;

        final var classDocs = new HashMap<String, ClassDoc>();
        xmlFiles.forEach(file -> classDocs.putAll(XmlJavadocParser.parse(file)));
        return new XmlJavadoc(classDocs);
    }

    @Override
    public String classComment(final Class<?> aClass) {
        return classDoc(aClass).map(ClassDoc::fullComment).orElse("");
    }

    @Override
    public String memberComment(final AnnotatedElement member) {
        return switch (member) {
            case Field field -> classDoc(field.getDeclaringClass()).map(doc -> doc.field(field.getName())).orElse("");
            case Method method -> classDoc(method.getDeclaringClass()).map(doc -> doc.method(method.getName())).orElse("");
            case RecordComponent component -> classDoc(component.getDeclaringRecord()).map(doc -> doc.param(component.getName())).orElse("");
            default -> "";
        };
    }

    private Optional<ClassDoc> classDoc(final Class<?> aClass) {
        return Optional.ofNullable(aClass.getCanonicalName()).map(classDocs::get);
    }
}
