package io.github.manoelcampos.java2ts.javadoc;

import io.github.manoelcampos.java2ts.javadoc.ClassDoc.DocTag;
import io.github.manoelcampos.java2ts.javadoc.xml.DocumentedXml;
import io.github.manoelcampos.java2ts.javadoc.xml.JavadocXml;
import io.github.manoelcampos.java2ts.javadoc.xml.MemberXml;
import io.github.manoelcampos.java2ts.javadoc.xml.TypeXml;
import jakarta.xml.bind.JAXB;

import java.nio.file.Path;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.Function;
import java.util.stream.Collectors;

/**
 * Parses the XML files generated by the
 * <a href="https://github.com/manticore-projects/xml-doclet">xml-doclet</a>, using JAXB.
 * @author Manoel Campos
 */
public final class XmlJavadocParser {
    private static final String PARAM_TAG = "param";
    private static final String RETURN_TAG = "return";

    private XmlJavadocParser() {/**/}

    /**
     * Parses a JavaDoc XML file.
     * @param xmlFile the XML file generated by the xml-doclet
     * @return a map where each key is the canonical name of a class and the value is its documentation
     */
    public static Map<String, ClassDoc> parse(final Path xmlFile) {
        final JavadocXml root = JAXB.unmarshal(xmlFile.toFile(), JavadocXml.class);
        return root.types().collect(Collectors.toMap(TypeXml::getQualified, XmlJavadocParser::classDoc, (a, b) -> a, LinkedHashMap::new));
    }

    private static ClassDoc classDoc(final TypeXml type) {
        final List<DocTag> allTags = tags(type);
        final List<DocTag> tags = allTags.stream().filter(tag -> !tag.name().equals(PARAM_TAG)).toList();
        final Map<String, String> params = allTags.stream()
                                                  .flatMap(tag -> tag.textIf(PARAM_TAG).stream())
                                                  .map(XmlJavadocParser::splitParam)
                                                  .collect(Collectors.toMap(DocTag::name, DocTag::text, (a, b) -> a));

        return new ClassDoc(comment(type), tags, params, fieldComments(type), methodComments(type));
    }

    private static List<DocTag> tags(final DocumentedXml element) {
        return element.getTags().stream()
                      .map(tag -> new DocTag(tag.getName(), CommentCleaner.tagText(tag.getName(), tag.getText())))
                      .toList();
    }

    /**
     * {@return a tag with the parameter name and its description, from the text of a {@code @param} tag}
     */
    private static DocTag splitParam(final String paramText) {
        final String[] parts = paramText.strip().split("\\s+", 2);
        return new DocTag(parts[0], parts.length > 1 ? parts[1] : "");
    }

    private static String comment(final DocumentedXml element) {
        return CommentCleaner.clean(element.getComment());
    }

    private static Map<String, String> fieldComments(final TypeXml type) {
        return commentsByName(type.getFields(), XmlJavadocParser::comment);
    }

    /**
     * {@return the comments of methods without parameters (possible getters), where the key is the method name}
     * When a method has no comment, its {@code @return} tag is used.
     */
    private static Map<String, String> methodComments(final TypeXml type) {
        final List<MemberXml> methods = type.getMethods().stream().filter(method -> !method.hasParameters()).toList();
        return commentsByName(methods, XmlJavadocParser::methodComment);
    }

    private static String methodComment(final MemberXml method) {
        final String comment = comment(method);
        return comment.isBlank() ? returnTag(method) : comment;
    }

    private static String returnTag(final MemberXml method) {
        return tags(method).stream().flatMap(tag -> tag.textIf(RETURN_TAG).stream()).findFirst().orElse("");
    }

    private static Map<String, String> commentsByName(final List<MemberXml> members, final Function<MemberXml, String> commentFn) {
        return members.stream()
                      .map(member -> Map.entry(member.getName(), commentFn.apply(member)))
                      .filter(entry -> !entry.getValue().isBlank())
                      .collect(Collectors.toMap(Map.Entry::getKey, Map.Entry::getValue, (a, b) -> a));
    }
}
