package io.github.manoelcampos.java2ts.javadoc.xml;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;

import java.util.ArrayList;
import java.util.List;
import java.util.stream.Stream;

/**
 * The root element of the XML file generated by the
 * <a href="https://github.com/manticore-projects/xml-doclet">xml-doclet</a>,
 * mapped using JAXB. Only the elements needed to get the documentation are mapped.
 * @author Manoel Campos
 */
@XmlRootElement(name = "root")
@XmlAccessorType(XmlAccessType.FIELD)
public class JavadocXml {
    /**
     * Creates a {@link JavadocXml} (used by JAXB).
     */
    public JavadocXml() {/**/}

    @XmlElement(name = "package")
    private List<PackageXml> packages = new ArrayList<>();

    /**
     * {@return all classes, interfaces and enums inside all packages}
     */
    public Stream<TypeXml> types() {
        return packages.stream().flatMap(PackageXml::types);
    }
}
