package io.github.manoelcampos.java2ts.sample.model;

import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.MappedSuperclass;
import org.jspecify.annotations.Nullable;

/**
 * Base class for JPA entities.
 */
@MappedSuperclass
public abstract class AbstractBaseModel implements BaseModel {
    /** Unique identifier generated by the database. */
    @Id @GeneratedValue(strategy = GenerationType.IDENTITY)
    private @Nullable Long id;

    @Override
    public @Nullable Long getId() {
        return id;
    }

    public void setId(final @Nullable Long id) {
        this.id = id;
    }
}
