package io.github.manoelcampos.java2ts;

import io.github.manoelcampos.java2ts.config.ClassSelection;
import io.github.manoelcampos.java2ts.config.DateMapping;
import io.github.manoelcampos.java2ts.config.NullabilityDefinition;
import io.github.manoelcampos.java2ts.config.OptionalPropertiesDeclaration;
import io.github.manoelcampos.java2ts.config.Settings;
import io.github.manoelcampos.java2ts.fixtures.Address;
import io.github.manoelcampos.java2ts.fixtures.EmptyEnum;
import io.github.manoelcampos.java2ts.fixtures.Measurements;
import io.github.manoelcampos.java2ts.fixtures.Outer;
import io.github.manoelcampos.java2ts.fixtures.Person;
import io.github.manoelcampos.java2ts.fixtures.PersonDTO;
import io.github.manoelcampos.java2ts.fixtures.PersonPage;
import io.github.manoelcampos.java2ts.fixtures.Wildcards;
import io.github.manoelcampos.java2ts.scan.ClassPathContext;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.CsvSource;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.Map;

import static io.github.manoelcampos.java2ts.TestSettings.FIXTURES_PACKAGE;
import static org.junit.jupiter.api.Assertions.assertAll;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * End-to-end tests converting the fixture classes to TypeScript.
 */
class Java2TsTest {
    private static final List<Class<?>> ALL_FIXTURES =
        List.of(Person.class, PersonPage.class, PersonDTO.class, Wildcards.class, Outer.class, EmptyEnum.class);

    private static String generate(final Settings settings, final Class<?>... classes) {
        return new Java2Ts(settings).generate(List.of(classes));
    }

    private static String generateAll() {
        return new Java2Ts(TestSettings.builder().build()).generate(ALL_FIXTURES);
    }

    private static void assertContainsAll(final String output, final String... expected) {
        assertAll(java.util.Arrays.stream(expected).map(line -> () -> assertTrue(output.contains(line), () -> "Missing: " + line + "\nin:\n" + output)));
    }

    @Test
    void alwaysIncludesGeneratedFileCommentWithoutDateWhenNoFileDate() {
        final String output = generateAll();
        assertTrue(output.startsWith("/* tslint:disable */\n/* eslint-disable */\n// This file is generated by java2ts and must not be manually changed.\n"));
    }

    @Test
    void includesDateInCommentWhenNoFileDateIsFalse() {
        final String output = generate(TestSettings.builder().noFileDate(false).build(), Address.class);
        assertTrue(output.contains("// This file is generated by java2ts on "));
    }

    @Test
    void ignoresJdkInterfacesSuchAsSerializableAndComparable() {
        final String output = generateAll();
        assertContainsAll(output, "export interface BaseModel {", "export interface AbstractModel extends BaseModel {\n}");
        assertFalse(output.contains("Serializable"));
        assertFalse(output.contains("Comparable"));
    }

    @Test
    void convertsBeanProperties() {
        assertContainsAll(generateAll(),
            "export interface Person extends AbstractModel {",
            "    name: string;\n    age: number;\n",
            "birthDate?: string | null;",
            "createdAt?: string | null;",
            "addresses?: Address[] | null;",
            "scores?: Record<string, number> | null;",
            "status?: Status | null;",
            "tags?: string[] | null;",
            "matrix?: number[][] | null;",
            "active: boolean;",
            "photo?: string | null;",
            "code?: string | null;",
            "salary?: number | null;",
            "partner?: Person | null;",
            "initial: string;",
            "nonPublicFieldWithJsonProperty?: string | null;",
            "fullDescription?: string | null;");
    }

    @Test
    void readsRequiredAnnotationsWithClassRetentionFromClassFiles() {
        final var settings = TestSettings.builder().requiredAnnotations(java.util.Set.of(io.github.manoelcampos.java2ts.fixtures.ClassRetained.class.getName())).build();
        final var model = io.github.manoelcampos.java2ts.fixtures.ClassRetainedModel.class;
        assertContainsAll(generate(settings, model, io.github.manoelcampos.java2ts.fixtures.ClassRetainedModel.Rec.class),
            "    fieldAnnotated: string;", "    getterAnnotated: string;", "    notAnnotated?: string | null;",
            "    annotated: string;", "    other?: string | null;");
    }

    @Test
    void primitivePropertiesAreAlwaysRequired() {
        assertContainsAll(generateAll(), "    value: number;\n", "    age: number;\n");
    }

    @Test
    void handlesJacksonAnnotations() {
        final String output = generateAll();
        assertContainsAll(output, "\"e-mail\"?: string | null;", "export type Status = \"ACTIVE\" | \"INACTIVE\" | \"removed\";");
        assertFalse(output.contains("password"));
        assertFalse(output.contains("isNew"));
        assertFalse(output.contains("ignored"));
    }

    @Test
    void doesNotIncludeNonGettersNorFieldsWithoutGetters() {
        final String output = generateAll();
        assertFalse(output.contains("sameId"));
        assertFalse(output.contains("defaultName"));
        assertFalse(output.contains("fieldWithoutGetter"));
        assertFalse(output.contains("label"));
    }

    @Test
    void convertsJavaOptionalToOptionalProperty() {
        assertContainsAll(generateAll(), "nickname?: string | null;", "luckyNumber?: number | null;");
    }

    @Test
    void convertsJavaOptionalToOptionalPropertyEvenWithoutRequiredAnnotations() {
        final var settings = Settings.builder()
                                     .requiredAnnotations(java.util.Set.of())
                                     .optionalPropertiesDeclaration(OptionalPropertiesDeclaration.questionMark)
                                     .build();
        assertContainsAll(generate(settings, Person.class), "nickname?: string;", "luckyNumber?: number;", "    name: string;");
    }

    @Test
    void convertsRecordsAndGenerics() {
        assertContainsAll(generateAll(),
            "export interface Address {\n    street: string;\n    number?: number | null;\n    complements?: (string | null)[] | null;\n}",
            "export interface ModelRecord<T> {\n}",
            "export interface PersonDTO extends ModelRecord<Person> {",
            "nested?: Record<string, Record<number, Address>[]> | null;",
            "export interface Page<T> {\n    items?: T[] | null;\n    total: number;\n}",
            "export interface PersonPage extends Page<Person> {\n    lastPage: boolean;\n}",
            "countryId: number;");
    }

    @Test
    void convertsWildcardsRawTypesAndJdkTypes() {
        assertContainsAll(generateAll(),
            "export interface Wildcards<T> {",
            "unknown?: any[] | null;",
            "numbers?: number[] | null;",
            "superIntegers?: any[] | null;",
            "rawList?: any[] | null;",
            "rawMap?: Record<string, any> | null;",
            "rawPage?: Page<any> | null;",
            "genericArray?: T[] | null;",
            "values?: T[] | null;",
            "anything?: any;",
            "jdkClass?: any;");
    }

    @Test
    void convertsGenericBoundsAndMapKeys() {
        assertContainsAll(generate(TestSettings.builder().build(), io.github.manoelcampos.java2ts.fixtures.Box.class),
            "export interface Box<N extends number, P extends Page<N> & ModelRecord<N>, C> {",
            "countByStatus?: Partial<Record<Status, number>> | null;",
            "namesById?: Record<number, string> | null;",
            "objectKeys?: Record<string, string> | null;",
            "    /**\n     * @deprecated\n     */\n    oldField?: string | null;");
    }

    @Test
    void addsDeprecatedTagToDeprecatedClassesAndEnums() {
        final var settings = TestSettings.builder().build();
        final String output = generate(settings, io.github.manoelcampos.java2ts.fixtures.OldModel.class, io.github.manoelcampos.java2ts.fixtures.OldStatus.class);
        assertContainsAll(output, "/**\n * @deprecated\n */\nexport interface OldModel {", "/**\n * @deprecated\n */\nexport type OldStatus = \"YES\" | \"NO\";");
    }

    @Test
    void convertsNestedClassesAndEmptyEnums() {
        assertContainsAll(generateAll(), "export interface Inner {", "inner?: Inner | null;", "export type EmptyEnum = never;");
    }

    @Test
    void sortsInterfacesBeforeTypeAliases() {
        final String output = generateAll();
        assertTrue(output.indexOf("export interface Wildcards") < output.indexOf("export type EmptyEnum"));
        assertTrue(output.indexOf("export interface Address") < output.indexOf("export interface Person "));
    }

    @ParameterizedTest
    @CsvSource(delimiter = '|', textBlock = """
        questionMark                | number?: number | null;
        questionMarkAndNullableType | number?: number | null;
        nullableType                | number: number | null;
        nullableAndUndefinableType  | number: number | null | undefined;
        undefinableType             | number: number | null | undefined;
        """)
    void declaresOptionalProperties(final OptionalPropertiesDeclaration declaration, final String expected) {
        final var settings = TestSettings.builder().optionalPropertiesDeclaration(declaration).build();
        assertContainsAll(generate(settings, Address.class), expected, "street: string;");
    }

    @ParameterizedTest
    @CsvSource(delimiter = '|', textBlock = """
        nullInlineUnion             | complements?: (string | null)[];
        undefinedInlineUnion        | complements?: (string | undefined)[];
        nullAndUndefinedInlineUnion | complements?: (string | null | undefined)[];
        nullUnion                   | complements?: Nullable<string>[];
        """)
    void writesNullableTypes(final NullabilityDefinition definition, final String expected) {
        final var settings = TestSettings.builder()
                                         .nullabilityDefinition(definition)
                                         .optionalPropertiesDeclaration(OptionalPropertiesDeclaration.questionMark)
                                         .build();
        assertContainsAll(generate(settings, Address.class), expected);
    }

    @Test
    void declaresNullableAliasOnlyWhenUsed() {
        final var settings = TestSettings.builder().nullabilityDefinition(NullabilityDefinition.nullAndUndefinedUnion).build();
        assertContainsAll(generate(settings, Address.class), "export type Nullable<T> = T | null | undefined;", "number?: Nullable<number> | null;");
        assertFalse(generate(settings, EmptyEnum.class).contains("Nullable"));
    }

    @Test
    void removesUndefinedFromOptionalPropertiesWithQuestionMark() {
        final var settings = TestSettings.builder()
                                         .nullabilityDefinition(NullabilityDefinition.nullAndUndefinedInlineUnion)
                                         .optionalPropertiesDeclaration(OptionalPropertiesDeclaration.questionMark)
                                         .build();
        assertContainsAll(generate(settings, Address.class), "number?: number | null;");
    }

    @ParameterizedTest
    @CsvSource({"asDate,Date", "asString,string", "asNumber,number"})
    void mapsDates(final DateMapping mapping, final String tsType) {
        final var settings = TestSettings.builder().mapDate(mapping).build();
        assertContainsAll(generate(settings, Person.class), "birthDate?: %s | null;".formatted(tsType));
    }

    @Test
    void appliesCustomTypeMappingsConsideringNestedGenerics() {
        final var mappings = Map.of(
            "java.util.List<java.math.BigDecimal>", "number[]",
            "java.util.List[java.util.List[java.lang.Double]]", "Matrix",
            "java.lang.StringBuilder", "string");
        final var settings = Settings.builder().customTypeMappings(mappings).build();
        assertContainsAll(generate(settings, Measurements.class),
            "values?: number[] | null;", "names?: string[] | null;", "matrix?: Matrix | null;", "builder?: string | null;");
    }

    @Test
    void convertsExcludedClassesToAny() {
        final var selection = ClassSelection.of(null, null, List.of(Address.class.getName()), List.of("**.Status"), null, null, null);
        final var settings = TestSettings.builder().classSelection(selection).build();
        final String output = generate(settings, Person.class);
        assertContainsAll(output, "addresses?: any[] | null;", "status?: any;");
        assertFalse(output.contains("export interface Address"));
        assertFalse(output.contains("export type Status"));
    }

    @Test
    void failsWhenTwoClassesHaveTheSameName() {
        final var settings = TestSettings.builder().build();
        final var other = io.github.manoelcampos.java2ts.fixtures.other.Address.class;
        final var ex = assertThrows(IllegalStateException.class, () -> generate(settings, Address.class, other));
        assertTrue(String.valueOf(ex.getMessage()).contains("same name Address"));
    }

    @Test
    void generatesFileForClassesSelectedByPatterns(@TempDir final Path dir) throws IOException {
        final Path file = dir.resolve("sub/models.ts");
        final var settings = TestSettings.builder()
                                         .outputFile(file)
                                         .classPatterns(FIXTURES_PACKAGE + ".Person*", FIXTURES_PACKAGE + ".Address")
                                         .build();

        final Path generated = new Java2Ts(settings).generateFile(ClassPathContext.ofCurrentClassPath());
        final String content = Files.readString(generated);
        assertContainsAll(content, "export interface Person ", "export interface PersonDTO ", "export interface PersonPage ", "export interface Address ");
        assertFalse(content.contains("export interface Wildcards"));
    }

    @Test
    void generatesCodeForClassesSelectedByPatterns() {
        final var settings = TestSettings.builder().classPatterns(FIXTURES_PACKAGE + ".Outer").build();
        assertTrue(new Java2Ts(settings).generate(ClassPathContext.ofCurrentClassPath()).contains("export interface Outer"));
    }
}
