package io.github.manoelcampos.java2ts.fixtures;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.OptionalInt;
import java.util.Set;
import java.util.UUID;

/**
 * A person, like a Hibernate entity with getters generated by Lombok.
 */
@Entity
public class Person extends AbstractModel {
    /** The person's name. */
    @Required
    private String name;

    @Required
    private int age;

    private LocalDate birthDate;
    private LocalDateTime createdAt;
    private List<Address> addresses;
    private Map<String, Integer> scores;
    private Status status;

    @JsonIgnore
    private String password;

    private Optional<String> nickname;
    private OptionalInt luckyNumber;
    private String[] tags;
    private Set<List<Double>> matrix;
    private boolean active;
    private byte[] photo;
    private UUID code;
    private BigDecimal salary;
    private Person partner;

    @JsonProperty("e-mail")
    private String email;

    /** A public field without getter. */
    public char initial;

    @JsonProperty
    private String nonPublicFieldWithJsonProperty;

    private String fieldWithoutGetter;

    public String getName() { return name; }
    public int getAge() { return age; }
    public LocalDate getBirthDate() { return birthDate; }
    public LocalDateTime getCreatedAt() { return createdAt; }
    public List<Address> getAddresses() { return addresses; }
    public Map<String, Integer> getScores() { return scores; }
    public Status getStatus() { return status; }
    public String getPassword() { return password; }
    public Optional<String> getNickname() { return nickname; }
    public OptionalInt getLuckyNumber() { return luckyNumber; }
    public String[] getTags() { return tags; }
    public Set<List<Double>> getMatrix() { return matrix; }
    public boolean isActive() { return active; }
    public byte[] getPhoto() { return photo; }
    public UUID getCode() { return code; }
    public BigDecimal getSalary() { return salary; }
    public Person getPartner() { return partner; }
    public String getEmail() { return email; }

    /** A getter without backing field. */
    public String getFullDescription() { return name + " " + age; }

    /** A static method is not a getter. */
    public static String getDefaultName() { return ""; }
}
