package io.github.manoelcampos.java2ts.sample.model;

import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.MappedSuperclass;
import lombok.Getter;
import lombok.Setter;

/**
 * Base class for JPA entities.
 */
@MappedSuperclass @Getter @Setter
public abstract class AbstractBaseModel implements BaseModel {
    /** Unique identifier generated by the database. */
    @Id @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
}
