package io.github.manoelcampos.java2ts.sample.model;

import com.fasterxml.jackson.annotation.JsonIgnore;
import io.github.manoelcampos.dtogen.DTO;
import jakarta.persistence.ElementCollection;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.ManyToOne;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.Getter;
import lombok.Setter;
import org.jspecify.annotations.Nullable;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.EnumMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;

/**
 * A person, which is a JPA entity whose getters and setters are generated by Lombok.
 */
@Entity @Getter @Setter @DTO
public class Person extends AbstractBaseModel implements Comparable<Person> {
    /** The person's full name. */
    @NotNull @NotBlank
    private String name;

    /** The e-mail, which is optional. */
    @Email
    private String email;

    /** The birth date (converted to string, since it's serialized in ISO-8601 format). */
    @NotNull
    private LocalDate birthDate;

    /** When the person was registered. */
    private LocalDateTime createdAt;

    /** The country where the person lives (the DTO just has the country id). */
    @ManyToOne @NotNull @DTO.MapToId
    private Country country;

    /** The partner, if any. */
    @ManyToOne @Nullable @DTO.MapToId
    private Person partner;

    @NotNull @Enumerated(EnumType.STRING)
    private Status status = Status.ACTIVE;

    /** The person's phones. */
    @ElementCollection @NotNull
    private List<Phone> phones = new ArrayList<>();

    /** Primitive values are always required, since they can't be null. */
    private int loginAttempts;

    /** Ignored by Jackson, so it's not included in TypeScript nor in the DTO. */
    @JsonIgnore @DTO.Exclude
    private String password;

    /**
     * A property without a field, which is optional since it's an {@link Optional}.
     * @return the person's nickname, if any
     */
    public Optional<String> getNickname() {
        return Optional.ofNullable(name).map(n -> n.split(" ")[0]);
    }

    /**
     * {@return the number of logins by status, just to show how maps with enum keys are converted}
     */
    public Map<Status, Integer> getLoginsByStatus() {
        return new EnumMap<>(Status.class);
    }

    /**
     * Comparable is ignored when generating TypeScript.
     */
    @Override
    public int compareTo(final Person other) {
        return name.compareTo(other.name);
    }
}
