/* tslint:disable */
/* eslint-disable */
// This file is generated by java2ts and must not be manually changed.

/**
 * Base class for JPA entities.
 */
export interface AbstractBaseModel extends BaseModel {
}

/**
 * Base interface for all models.
 * {@link Serializable} is ignored when generating TypeScript, since it's not useful for the frontend.
 */
export interface BaseModel {
    /**
     * Returns the model id, which is null for objects not saved yet
     */
    id?: number | null;
}

/**
 * A country where people live.
 */
export interface Country extends AbstractBaseModel {
    /**
     * The country name.
     */
    name: string;
    /**
     * The ISO 3166-1 alpha-2 code, such as BR.
     */
    code: string;
}

/**
 * A {@link DTORecord Data Transfer Object} for {@link Country}.
 */
export interface CountryDTO extends DTORecord<Country> {
    id?: number | null;
    name: string;
    code: string;
}

/**
 * Interface to be implemented by DTO records.
 * @author Manoel Campos
 */
export interface DTORecord<T> {
}

/**
 * A generic page of results returned by a REST API.
 */
export interface PageResponse<T> {
    /**
     * the items in the page
     */
    content?: T[] | null;
    /**
     * the page number, starting from 0
     */
    page: number;
    /**
     * the total number of items in all pages
     */
    totalElements: number;
}

/**
 * A person, which is a JPA entity whose getters and setters are generated by Lombok.
 */
export interface Person extends AbstractBaseModel {
    /**
     * The person's full name.
     */
    name: string;
    /**
     * The e-mail, which is optional.
     */
    email?: string | null;
    /**
     * The birth date (converted to string, since it's serialized in ISO-8601 format).
     */
    birthDate: string;
    /**
     * When the person was registered.
     */
    createdAt?: string | null;
    /**
     * The country where the person lives (the DTO just has the country id).
     */
    country: Country;
    /**
     * The partner, if any.
     */
    partner?: Person | null;
    status: Status;
    /**
     * The person's phones.
     */
    phones: Phone[];
    /**
     * Primitive values are always required, since they can't be null.
     */
    loginAttempts: number;
    /**
     * Returns the number of logins by status, just to show how maps with enum keys are converted
     */
    loginsByStatus?: Partial<Record<Status, number>> | null;
    /**
     * A property without a field, which is optional since it's an {@link Optional}.
     */
    nickname?: string | null;
}

/**
 * A {@link DTORecord Data Transfer Object} for {@link Person}.
 */
export interface PersonDTO extends DTORecord<Person> {
    id?: number | null;
    name: string;
    email?: string | null;
    birthDate: string;
    createdAt?: string | null;
    countryId: number;
    partnerId?: number | null;
    status: Status;
    phones: Phone[];
    loginAttempts: number;
}

/**
 * A phone number, used as an embedded value.
 */
export interface Phone {
    /**
     * the phone type, such as mobile or home
     */
    type?: string | null;
    /**
     * the phone number
     */
    number?: string | null;
}

/**
 * A report showing nested generics and custom type mappings.
 */
export interface Report<N extends number> {
    /**
     * the report title
     */
    title: string;
    /**
     * a page of people DTOs
     */
    people: PageResponse<PersonDTO>;
    /**
     * a list of (latitude, longitude) pairs, mapped to a TypeScript tuple array in the plugin configuration
     */
    coordinates?: [number, number][] | null;
    /**
     * a list of tag groups, which is not affected by the custom mapping of the coordinates
     */
    tags?: string[][] | null;
    /**
     * totals by category
     */
    totals?: Record<string, N[]> | null;
    /**
     * the sum of all totals, mapped to string in the plugin configuration
     */
    grandTotal?: string | null;
}

/**
 * The status of a {@link Person}.
 * Enums are converted to string literal union types.
 */
export type Status = "ACTIVE" | "INACTIVE" | "BLOCKED";
