/* tslint:disable */
/* eslint-disable */
// This file is generated by java2ts and must not be manually changed.

import { z } from "zod";
import type { AbstractBaseModel, ApiError, BaseModel, Country, CountryDTO, DTORecord, PageResponse, Person, PersonDTO, Report, Status } from "./models.generated";
import { PhoneSchema } from "./validation.custom";

z.config(z.locales.ptBR());

/** Returns the current local date as an ISO-8601 string (yyyy-MM-dd), used to validate past and future dates. */
const localDate = (): string => {
    const now = new Date();
    return `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, "0")}-${String(now.getDate()).padStart(2, "0")}`;
};

export const AbstractBaseModelSchema: z.ZodType<AbstractBaseModel> = z.object({
    id: z.int().nullish(),
});

export const ApiErrorSchema: z.ZodType<ApiError> = z.object({
    status: z.int(),
    message: z.string(),
    timestamp: z.iso.datetime({ local: true }),
});

export const BaseModelSchema: z.ZodType<BaseModel> = z.object({
    id: z.int().nullish(),
});

export const CountrySchema: z.ZodType<Country> = z.object({
    id: z.int().nullish(),
    name: z.string().regex(/\S/),
    code: z.string().length(2),
});

export const CountryDTOSchema: z.ZodType<CountryDTO> = z.object({
    id: z.int().nullish(),
    name: z.string().regex(/\S/),
    code: z.string().length(2),
});

export const DTORecordSchema = <T>(TSchema: z.ZodType<T>): z.ZodType<DTORecord<T>> => z.object({
});

export const PageResponseSchema = <T>(TSchema: z.ZodType<T>): z.ZodType<PageResponse<T>> => z.object({
    content: z.array(TSchema).nullish(),
    page: z.int(),
    totalElements: z.int(),
});

export const PersonSchema: z.ZodType<Person> = z.object({
    id: z.int().nullish(),
    name: z.string().regex(/\S/).max(100),
    email: z.email().nullish(),
    birthDate: z.iso.date().refine(v => v < localDate()),
    createdAt: z.iso.datetime({ local: true }).nullish(),
    get country() { return CountrySchema; },
    get partner() { return PersonSchema.nullish(); },
    get status() { return StatusSchema; },
    get phones() { return z.array(PhoneSchema); },
    loginAttempts: z.int().gte(0),
    get loginsByStatus() { return z.partialRecord(StatusSchema, z.int()).nullish(); },
    nickname: z.string().nullish(),
});

export const PersonDTOSchema: z.ZodType<PersonDTO> = z.object({
    id: z.int().nullish(),
    name: z.string().regex(/\S/).max(100),
    email: z.email().nullish(),
    birthDate: z.iso.date().refine(v => v < localDate()),
    createdAt: z.iso.datetime({ local: true }).nullish(),
    countryId: z.int(),
    partnerId: z.int().nullish(),
    get status() { return StatusSchema; },
    get phones() { return z.array(PhoneSchema); },
    loginAttempts: z.int().gte(0),
});

export const ReportSchema = <N extends number>(NSchema: z.ZodType<N>): z.ZodType<Report<N>> => z.object({
    title: z.string(),
    get people() { return PageResponseSchema(PersonDTOSchema); },
    coordinates: z.array(z.tuple([z.number(), z.number()])).nullish(),
    tags: z.array(z.array(z.string())).nullish(),
    totals: z.record(z.string(), z.array(NSchema)).nullish(),
    grandTotal: z.string().regex(/^-?\d+(\.\d+)?$/).nullish(),
});

export const StatusSchema = z.enum(["ACTIVE", "INACTIVE", "BLOCKED"]) satisfies z.ZodType<Status>;
