package io.github.manoelcampos.java2ts.parser;

import java.lang.reflect.AnnotatedElement;
import java.lang.reflect.AnnotatedType;
import java.lang.reflect.Field;
import java.lang.reflect.Method;
import java.lang.reflect.Modifier;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Comparator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.stream.Collectors;
import java.util.stream.Stream;

/**
 * Extracts the properties of Java Beans (such as POJOs, entities and interfaces), as Jackson does:
 * properties are defined by public getters (including the ones generated by Lombok),
 * public fields and fields annotated with {@code @JsonProperty}.
 *
 * <p>Annotations and documentation of a property are got from its getters and its backing field
 * (the field with the same name of the property). Properties are sorted according to the declaration
 * order of their fields, followed by the properties without fields, sorted by name.</p>
 * @author Manoel Campos
 */
public final class BeanPropertyExtractor implements PropertyExtractor {
    /**
     * Creates a {@link BeanPropertyExtractor}.
     */
    public BeanPropertyExtractor() {/**/}

    @Override
    public List<JavaProperty> extract(final Class<?> aClass) {
        final List<Field> fields = Members.instanceFields(aClass);
        final Map<String, List<Method>> getters = gettersByPropertyName(aClass);

        final Stream<JavaProperty> getterProps = getters.entrySet().stream().map(entry -> getterProperty(entry.getKey(), entry.getValue(), fields));
        final Stream<JavaProperty> fieldProps = fields.stream()
                                                      .filter(field -> !getters.containsKey(field.getName()) && isSerializableField(field))
                                                      .map(BeanPropertyExtractor::fieldProperty);

        return Stream.concat(getterProps, fieldProps).sorted(fieldOrder(fields)).toList();
    }

    private static Map<String, List<Method>> gettersByPropertyName(final Class<?> aClass) {
        return Arrays.stream(aClass.getMethods())
                     .filter(Getters::isGetter)
                     .collect(Collectors.groupingBy(Getters::propertyName, LinkedHashMap::new, Collectors.toList()));
    }

    private static JavaProperty getterProperty(final String name, final List<Method> getters, final List<Field> fields) {
        final var elements = new ArrayList<AnnotatedElement>();
        final Optional<Field> field = backingField(name, fields);
        field.ifPresent(elements::add);
        elements.addAll(getters);
        return new JavaProperty(name, propertyType(mostSpecific(getters), field), elements);
    }

    /**
     * {@return the type of a property defined by a getter}
     * If the backing field has the same type of the getter, the field type is used,
     * since getters generated by Lombok don't copy annotations of generic type arguments
     * (such as {@code List<@NotBlank String>}).
     */
    private static AnnotatedType propertyType(final Method getter, final Optional<Field> field) {
        return field.filter(aField -> aField.getGenericType().equals(getter.getGenericReturnType()))
                    .map(Field::getAnnotatedType)
                    .orElseGet(getter::getAnnotatedReturnType);
    }

    private static JavaProperty fieldProperty(final Field field) {
        return new JavaProperty(field.getName(), field.getAnnotatedType(), List.of(field));
    }

    private static boolean isSerializableField(final Field field) {
        return Modifier.isPublic(field.getModifiers()) || JacksonAnnotations.hasJsonProperty(field);
    }

    /**
     * {@return the field with the same name of a property, which is the closest to the class
     * if there are fields with the same name in the class hierarchy}
     */
    private static Optional<Field> backingField(final String propertyName, final List<Field> fields) {
        return fields.stream().filter(field -> field.getName().equals(propertyName)).reduce((first, second) -> second);
    }

    /**
     * {@return the getter declared in the most specific class/interface, among getters overriding each other}
     */
    private static Method mostSpecific(final List<Method> getters) {
        return getters.stream()
                      .reduce((m1, m2) -> m2.getDeclaringClass().isAssignableFrom(m1.getDeclaringClass()) ? m1 : m2)
                      .orElseThrow();
    }

    private static Comparator<JavaProperty> fieldOrder(final List<Field> fields) {
        final List<String> fieldNames = fields.stream().map(Field::getName).toList();
        final Comparator<JavaProperty> byFieldIndex = Comparator.comparingInt(prop -> {
            final int index = fieldNames.indexOf(prop.name());
            return index < 0 ? Integer.MAX_VALUE : index;
        });

        return byFieldIndex.thenComparing(JavaProperty::name);
    }
}
