package io.github.manoelcampos.java2ts.writer;

import java.time.Clock;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

/**
 * Creates the comment written at the beginning of the generated TypeScript file,
 * which states that the file is generated and must not be manually changed.
 *
 * @param includeDate if the generation date is included in the comment
 * @param clock the clock used to get the generation date
 * @author Manoel Campos
 */
public record FileHeader(boolean includeDate, Clock clock) {
    private static final DateTimeFormatter DATE_FORMAT = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
    private static final String LINTER_DIRECTIVES = "/* tslint:disable */\n/* eslint-disable */\n";

    /**
     * Creates a header using the system clock.
     * @param includeDate if the generation date is included in the comment
     */
    public FileHeader(final boolean includeDate) {
        this(includeDate, Clock.systemDefaultZone());
    }

    /**
     * {@return the header text, ending with a blank line}
     */
    public String format() {
        final String date = includeDate ? " on " + LocalDateTime.now(clock).format(DATE_FORMAT) : "";
        return "%s// This file is generated by java2ts%s and must not be manually changed.\n\n".formatted(LINTER_DIRECTIVES, date);
    }
}
