package io.github.manoelcampos.java2ts.config;

import java.nio.file.Path;
import java.util.List;
import java.util.Map;
import java.util.Set;

import static java.util.Objects.requireNonNull;

/**
 * All the settings used to convert Java classes to TypeScript.
 * Use {@link #builder()} to create an instance with default values for the settings not set.
 *
 * @param outputFileType the kind of TypeScript file to generate
 * @param outputFile the path of the TypeScript file to generate
 * @param nullabilityDefinition how nullable types are written
 * @param optionalPropertiesDeclaration how optional properties are written
 * @param nullableAnnotations fully qualified names of annotations that make a property (or a type usage) nullable
 * @param requiredAnnotations fully qualified names of annotations that make a property required.
 *                            If not empty, properties without any of these annotations become optional.
 * @param javadocXmlFiles XML files generated by the xml-doclet, from where JavaDocs are copied
 *                        to the TypeScript declarations
 * @param classSelection defines which Java classes are converted
 * @param customTypeMappings maps a Java type name (which may include generic type arguments, even nested ones,
 *                           such as {@code java.util.List<java.math.BigDecimal>})
 *                           to the TypeScript type it must be converted to
 * @param mapDate how date/time types are converted
 * @param noFileDate if true, the comment at the beginning of the generated file doesn't include
 *                   the generation date, avoiding changes in the file when nothing else changed
 * @author Manoel Campos
 */
public record Settings(
    OutputFileType outputFileType,
    Path outputFile,
    NullabilityDefinition nullabilityDefinition,
    OptionalPropertiesDeclaration optionalPropertiesDeclaration,
    Set<String> nullableAnnotations,
    Set<String> requiredAnnotations,
    List<Path> javadocXmlFiles,
    ClassSelection classSelection,
    Map<String, String> customTypeMappings,
    DateMapping mapDate,
    boolean noFileDate)
{
    /**
     * Creates a {@link Settings}, validating the components and making immutable copies of collections.
     */
    public Settings {
        requireNonNull(outputFileType, "outputFileType");
        requireNonNull(outputFile, "outputFile");
        requireNonNull(nullabilityDefinition, "nullabilityDefinition");
        requireNonNull(optionalPropertiesDeclaration, "optionalPropertiesDeclaration");
        requireNonNull(mapDate, "mapDate");
        requireNonNull(classSelection, "classSelection");
        nullableAnnotations = Set.copyOf(nullableAnnotations);
        requiredAnnotations = Set.copyOf(requiredAnnotations);
        javadocXmlFiles = List.copyOf(javadocXmlFiles);
        customTypeMappings = Map.copyOf(customTypeMappings);
    }

    /**
     * {@return a new builder to create a {@link Settings} object with default values}
     */
    public static SettingsBuilder builder() {
        return new SettingsBuilder();
    }
}
