package io.github.manoelcampos.java2ts.config;

import java.nio.file.Path;
import java.util.Collection;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * Builds {@link Settings} objects, using the {@link Defaults} for the settings not set.
 * @author Manoel Campos
 */
public final class SettingsBuilder {
    /** Default path of the generated file when none is given. */
    public static final Path DEFAULT_OUTPUT_FILE = Path.of("target", "java2ts.ts");

    private OutputFileType outputFileType = OutputFileType.valueOf(Defaults.OUTPUT_FILE_TYPE);
    private Path outputFile = DEFAULT_OUTPUT_FILE;
    private NullabilityDefinition nullabilityDefinition = NullabilityDefinition.valueOf(Defaults.NULLABILITY_DEFINITION);
    private OptionalPropertiesDeclaration optionalPropertiesDeclaration = OptionalPropertiesDeclaration.valueOf(Defaults.OPTIONAL_PROPERTIES_DECLARATION);
    private Set<String> nullableAnnotations = Defaults.NULLABLE_ANNOTATIONS;
    private Set<String> requiredAnnotations = Defaults.REQUIRED_ANNOTATIONS;
    private List<Path> javadocXmlFiles = List.of();
    private ClassSelection classSelection = ClassSelection.EMPTY;
    private Map<String, String> customTypeMappings = Map.of();
    private DateMapping mapDate = DateMapping.valueOf(Defaults.MAP_DATE);
    private boolean readonlyProperties = Boolean.parseBoolean(Defaults.READONLY_PROPERTIES);
    private boolean noFileDate = Boolean.parseBoolean(Defaults.NO_FILE_DATE);

    SettingsBuilder() {/**/}

    /**
     * Sets the kind of TypeScript file to generate.
     * @param outputFileType the kind of file, which defines the default file extension
     * @return this builder
     */
    public SettingsBuilder outputFileType(final OutputFileType outputFileType) {
        this.outputFileType = outputFileType;
        return this;
    }

    /**
     * Sets the path of the TypeScript file to generate.
     * @param outputFile the file path, whose parent directories are created if needed
     * @return this builder
     */
    public SettingsBuilder outputFile(final Path outputFile) {
        this.outputFile = outputFile;
        return this;
    }

    /**
     * Sets how nullable types are written.
     * @param nullabilityDefinition the definition used to write nullable types (inline unions or the Nullable alias)
     * @return this builder
     */
    public SettingsBuilder nullabilityDefinition(final NullabilityDefinition nullabilityDefinition) {
        this.nullabilityDefinition = nullabilityDefinition;
        return this;
    }

    /**
     * Sets how optional properties are declared.
     * @param declaration the declaration that defines if a question mark and/or null/undefined are added to optional properties
     * @return this builder
     */
    public SettingsBuilder optionalPropertiesDeclaration(final OptionalPropertiesDeclaration declaration) {
        this.optionalPropertiesDeclaration = declaration;
        return this;
    }

    /**
     * Sets the annotations that make properties and types nullable.
     * @param nullableAnnotations fully qualified names of annotations; annotated properties/types accept null
     * @return this builder
     */
    public SettingsBuilder nullableAnnotations(final Collection<String> nullableAnnotations) {
        this.nullableAnnotations = Set.copyOf(nullableAnnotations);
        return this;
    }

    /**
     * Sets the annotations that make properties required.
     * @param requiredAnnotations fully qualified names of annotations; if not empty, properties without them become optional
     * @return this builder
     */
    public SettingsBuilder requiredAnnotations(final Collection<String> requiredAnnotations) {
        this.requiredAnnotations = Set.copyOf(requiredAnnotations);
        return this;
    }

    /**
     * Sets the XML files generated by the xml-doclet, from where JavaDocs are copied.
     * @param javadocXmlFiles the XML files; JavaDocs are not copied if the list is empty
     * @return this builder
     */
    public SettingsBuilder javadocXmlFiles(final List<Path> javadocXmlFiles) {
        this.javadocXmlFiles = javadocXmlFiles;
        return this;
    }

    /**
     * Sets which classes are converted.
     * @param classSelection the criteria to select the classes to convert and the ones to exclude
     * @return this builder
     */
    public SettingsBuilder classSelection(final ClassSelection classSelection) {
        this.classSelection = classSelection;
        return this;
    }

    /**
     * Sets the classes to convert, using glob patterns.
     * It's a shortcut for {@link #classSelection(ClassSelection)} when only patterns are needed.
     * @param classPatterns the patterns of the classes to convert
     * @return this builder
     */
    public SettingsBuilder classPatterns(final String... classPatterns) {
        this.classSelection = ClassSelection.ofPatterns(List.of(classPatterns));
        return this;
    }

    /**
     * Sets custom conversions for specific Java types.
     * @param customTypeMappings a map where each key is a Java type name (that may include generic type arguments)
     *                           and the value is the TypeScript type it is converted to
     * @return this builder
     */
    public SettingsBuilder customTypeMappings(final Map<String, String> customTypeMappings) {
        this.customTypeMappings = customTypeMappings;
        return this;
    }

    /**
     * Sets how date/time types are converted.
     * @param mapDate the TypeScript type that dates are converted to
     * @return this builder
     */
    public SettingsBuilder mapDate(final DateMapping mapDate) {
        this.mapDate = mapDate;
        return this;
    }

    /**
     * Sets if record components and final fields are declared as read-only properties.
     * @param readonlyProperties true to declare them as read-only (such as {@code readonly name: string}), false otherwise
     * @return this builder
     */
    public SettingsBuilder readonlyProperties(final boolean readonlyProperties) {
        this.readonlyProperties = readonlyProperties;
        return this;
    }

    /**
     * Sets if the generation date is left out of the comment at the beginning of the file.
     * @param noFileDate true to leave the date out (avoiding changes in the file when nothing else changed), false to include it
     * @return this builder
     */
    public SettingsBuilder noFileDate(final boolean noFileDate) {
        this.noFileDate = noFileDate;
        return this;
    }

    /**
     * {@return a new {@link Settings} object with the values defined in this builder}
     */
    public Settings build() {
        return new Settings(
            outputFileType, outputFile, nullabilityDefinition, optionalPropertiesDeclaration,
            nullableAnnotations, requiredAnnotations, javadocXmlFiles, classSelection,
            customTypeMappings, mapDate, readonlyProperties, noFileDate);
    }
}
