package io.github.manoelcampos.java2ts.writer;

import org.junit.jupiter.api.Test;

import java.time.Clock;
import java.time.Instant;
import java.time.ZoneOffset;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

class FileHeaderTest {
    private static final Clock CLOCK = Clock.fixed(Instant.parse("2026-10-03T10:20:30Z"), ZoneOffset.UTC);

    @Test
    void includesDate() {
        assertTrue(new FileHeader(true, CLOCK).format().contains("// This file is generated by java2ts on 2026-10-03 10:20:30 and must not be manually changed.\n"));
    }

    @Test
    void excludesDate() {
        final var expected = "/* tslint:disable */\n/* eslint-disable */\n// This file is generated by java2ts and must not be manually changed.\n\n";
        assertEquals(expected, new FileHeader(false).format());
    }
}
