package io.github.manoelcampos.java2ts.maven;

import io.github.manoelcampos.java2ts.Java2Ts;
import io.github.manoelcampos.java2ts.config.ClassSelection;
import io.github.manoelcampos.java2ts.config.DateMapping;
import io.github.manoelcampos.java2ts.config.Defaults;
import io.github.manoelcampos.java2ts.config.NullabilityDefinition;
import io.github.manoelcampos.java2ts.config.OptionalPropertiesDeclaration;
import io.github.manoelcampos.java2ts.config.OutputFileType;
import io.github.manoelcampos.java2ts.config.Settings;
import io.github.manoelcampos.java2ts.javadoc.XmlDocletRunner;
import io.github.manoelcampos.java2ts.parser.type.CustomTypeMappings;
import io.github.manoelcampos.java2ts.scan.ClassPathContext;
import org.apache.maven.artifact.DependencyResolutionRequiredException;
import org.apache.maven.plugin.AbstractMojo;
import org.apache.maven.plugin.MojoExecutionException;
import org.apache.maven.plugins.annotations.Component;
import org.apache.maven.plugins.annotations.LifecyclePhase;
import org.apache.maven.plugins.annotations.Mojo;
import org.apache.maven.plugins.annotations.Parameter;
import org.apache.maven.plugins.annotations.ResolutionScope;
import org.apache.maven.project.MavenProject;
import org.eclipse.aether.RepositorySystem;
import org.eclipse.aether.RepositorySystemSession;
import org.eclipse.aether.repository.RemoteRepository;
import org.jspecify.annotations.Nullable;

import java.io.File;
import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.Set;

import static java.util.Objects.requireNonNull;

/**
 * Generates a TypeScript file from the Java classes of a project.
 * By default, it runs in the compile phase, right after the project classes are compiled.
 * Check the README for details about each parameter.
 * @author Manoel Campos
 */
@Mojo(name = "generate", defaultPhase = LifecyclePhase.COMPILE,
      requiresDependencyResolution = ResolutionScope.COMPILE, threadSafe = true)
public class GenerateMojo extends AbstractMojo {
    /**
     * Creates a {@link GenerateMojo} (instantiated by Maven).
     */
    public GenerateMojo() {/**/}

    private static final String JAVADOC_XML_FILE = "java2ts/javadoc.xml";

    @Parameter(defaultValue = "${project}", readonly = true, required = true)
    MavenProject project;

    /** The kind of TypeScript file to generate: declarationFile (.d.ts) or implementationFile (.ts). */
    @Parameter(property = "java2ts.outputFileType", defaultValue = Defaults.OUTPUT_FILE_TYPE)
    OutputFileType outputFileType = OutputFileType.valueOf(Defaults.OUTPUT_FILE_TYPE);

    /** The TypeScript file to generate. Default: target/[artifactId].ts (or .d.ts for declarationFile) */
    @Parameter(property = "java2ts.outputFile")
    @Nullable File outputFile;

    @Parameter(property = "java2ts.nullabilityDefinition", defaultValue = Defaults.NULLABILITY_DEFINITION)
    NullabilityDefinition nullabilityDefinition = NullabilityDefinition.valueOf(Defaults.NULLABILITY_DEFINITION);

    @Parameter(property = "java2ts.optionalPropertiesDeclaration", defaultValue = Defaults.OPTIONAL_PROPERTIES_DECLARATION)
    OptionalPropertiesDeclaration optionalPropertiesDeclaration = OptionalPropertiesDeclaration.valueOf(Defaults.OPTIONAL_PROPERTIES_DECLARATION);

    /** Annotations that make a property nullable. If not set, {@link Defaults#NULLABLE_ANNOTATIONS} are used. */
    @Parameter
    @Nullable List<String> nullableAnnotations;

    /** Annotations that make a property required. If not set, {@link Defaults#REQUIRED_ANNOTATIONS} are used. */
    @Parameter
    @Nullable List<String> requiredAnnotations;

    /** XML files generated by the xml-doclet, from where JavaDocs are copied. */
    @Parameter
    @Nullable List<File> javadocXmlFiles;

    @Parameter
    @Nullable List<String> classes;

    @Parameter
    @Nullable List<String> classPatterns;

    @Parameter
    @Nullable List<String> excludeClasses;

    @Parameter
    @Nullable List<String> excludeClassPatterns;

    @Parameter
    @Nullable List<String> classesWithAnnotations;

    @Parameter
    @Nullable List<String> classesImplementingInterfaces;

    @Parameter
    @Nullable List<String> classesExtendingClasses;

    /** Mappings in the format javaType:tsType, such as java.util.List[java.math.BigDecimal]:number[] */
    @Parameter
    @Nullable List<String> customTypeMappings;

    @Parameter(property = "java2ts.mapDate", defaultValue = Defaults.MAP_DATE)
    DateMapping mapDate = DateMapping.valueOf(Defaults.MAP_DATE);

    /** If true, the comment at the beginning of the generated file doesn't include the generation date. */
    /** If true, record components and final fields are declared as read-only properties. */
    @Parameter(property = "java2ts.readonlyProperties", defaultValue = Defaults.READONLY_PROPERTIES)
    boolean readonlyProperties = Boolean.parseBoolean(Defaults.READONLY_PROPERTIES);

    @Parameter(property = "java2ts.noFileDate", defaultValue = Defaults.NO_FILE_DATE)
    boolean noFileDate = Boolean.parseBoolean(Defaults.NO_FILE_DATE);

    /**
     * If true (the default), the JavaDocs of the project sources are automatically extracted (using the xml-doclet)
     * and copied to the TypeScript file. If the extraction fails, a warning is logged and the file is generated without docs.
     */
    @Parameter(property = "java2ts.javadoc", defaultValue = Defaults.JAVADOC)
    boolean javadoc = Boolean.parseBoolean(Defaults.JAVADOC);

    /** The version of the xml-doclet used when {@link #javadoc} is enabled. */
    @Parameter(property = "java2ts.xmlDocletVersion", defaultValue = Defaults.XML_DOCLET_VERSION)
    String xmlDocletVersion = Defaults.XML_DOCLET_VERSION;

    /** Skips the plugin execution. */
    @Parameter(property = "java2ts.skip", defaultValue = "false")
    boolean skip;

    @Component
    @Nullable RepositorySystem repositorySystem;

    @Parameter(defaultValue = "${repositorySystemSession}", readonly = true)
    @Nullable RepositorySystemSession repositorySession;

    @Parameter(defaultValue = "${project.remoteProjectRepositories}", readonly = true)
    @Nullable List<RemoteRepository> remoteRepositories;

    /** Resolves the xml-doclet jars. If null, they are resolved from the Maven repositories. */
    @Nullable DocletClasspathResolver docletResolver;

    @Override
    public void execute() throws MojoExecutionException {
        if (skip) {
            getLog().info("java2ts execution skipped");
            return;
        }

        try {
            final List<Path> classpath = compileClasspath();
            final Settings settings = settings(classpath);
            try (var classLoader = ProjectClassLoader.create(classpath)) {
                final Path file = new Java2Ts(settings).generateFile(new ClassPathContext(classLoader, classpath));
                getLog().info("TypeScript file generated at " + file);
            }
        } catch (final IOException | DependencyResolutionRequiredException | RuntimeException e) {
            throw new MojoExecutionException("Error generating TypeScript file: " + e.getMessage(), e);
        }
    }

    Settings settings(final List<Path> classpath) {
        final var selection = ClassSelection.of(
            classes, classPatterns, excludeClasses, excludeClassPatterns,
            classesWithAnnotations, classesImplementingInterfaces, classesExtendingClasses);

        return new Settings(
            outputFileType, outputFilePath(), nullabilityDefinition, optionalPropertiesDeclaration,
            annotationsOrDefault(nullableAnnotations, Defaults.NULLABLE_ANNOTATIONS),
            annotationsOrDefault(requiredAnnotations, Defaults.REQUIRED_ANNOTATIONS),
            javadocFiles(classpath), selection, CustomTypeMappings.parse(orEmpty(customTypeMappings)),
            mapDate, readonlyProperties, noFileDate);
    }

    private Path outputFilePath() {
        if (outputFile != null)
            return outputFile.toPath();

        final String fileName = project.getArtifactId() + outputFileType.extension();
        return Path.of(project.getBuild().getDirectory(), fileName);
    }

    /**
     * {@return the JavaDoc XML files given by the user, plus the one automatically generated
     * from the project sources when the javadoc extraction is enabled}
     */
    private List<Path> javadocFiles(final List<Path> classpath) {
        final var files = new ArrayList<>(orEmpty(javadocXmlFiles).stream().map(File::toPath).toList());
        if (javadoc)
            extractJavadoc(classpath).ifPresent(files::add);

        return files;
    }

    /**
     * Extracts the JavaDocs of the project sources into a XML file.
     * Since the extraction is enabled by default, any error just logs a warning instead of failing the build.
     * @param classpath the project classpath, required by the javadoc tool
     * @return an Optional with the generated XML file, or an empty Optional if there are no sources or the extraction failed
     */
    private Optional<Path> extractJavadoc(final List<Path> classpath) {
        final List<Path> sourceRoots = project.getCompileSourceRoots().stream().map(Path::of).toList();
        final Path outputXml = Path.of(project.getBuild().getDirectory(), JAVADOC_XML_FILE);
        getLog().info("Extracting JavaDocs using xml-doclet " + xmlDocletVersion);
        try {
            return new XmlDocletRunner(docletResolver().resolve(xmlDocletVersion)).run(sourceRoots, classpath, outputXml);
        } catch (final IllegalStateException | UncheckedIOException e) {
            getLog().warn("JavaDocs won't be copied to the TypeScript file. Set java2ts.javadoc to false to skip the extraction. " + e.getMessage());
            return Optional.empty();
        }
    }

    private DocletClasspathResolver docletResolver() {
        if (docletResolver == null) {
            docletResolver = new MavenDocletClasspathResolver(
                requireNonNull(repositorySystem, "repositorySystem"), requireNonNull(repositorySession, "repositorySession"),
                orEmpty(remoteRepositories));
        }

        return docletResolver;
    }

    private List<Path> compileClasspath() throws DependencyResolutionRequiredException {
        return project.getCompileClasspathElements().stream().map(Path::of).toList();
    }

    private static Set<String> annotationsOrDefault(final @Nullable List<String> annotations, final Set<String> defaults) {
        return annotations == null ? defaults : Set.copyOf(annotations);
    }

    private static <T> List<T> orEmpty(final @Nullable List<T> list) {
        return list == null ? List.of() : list;
    }
}
